# Generated by Django 4.2.11 on 2024-04-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstrapp', '0002_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.URLField(blank=True),
        ),
    ]
