# Generated by Django 4.2.11 on 2024-04-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstrapp', '0003_alter_images_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
