# Generated by Django 4.2.11 on 2024-04-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstrapp', '0005_alter_images_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=128),
        ),
    ]
